export const CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`;
export const USDT_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_USDT_CONTRACT_ADDRESS as `0x${string}`;

export const CONTRACT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "usdtAddress", type: "address" },
      { internalType: "address", name: "rewardTokenAddress", type: "address" },
      { internalType: "address", name: "feeWalletA", type: "address" },
      { internalType: "address", name: "feeWalletB", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AdminRenounced", type: "error" },
  { inputs: [], name: "ChapterAlreadyUnlocked", type: "error" },
  { inputs: [], name: "ContractNotAllowed", type: "error" },
  { inputs: [], name: "InvalidChapter", type: "error" },
  { inputs: [], name: "InvalidTrack", type: "error" },
  { inputs: [], name: "LibraryClosed", type: "error" },
  { inputs: [], name: "NoRoyalty", type: "error" },
  { inputs: [], name: "OnlyAdmin", type: "error" },
  { inputs: [], name: "OnlyOwner", type: "error" },
  { inputs: [], name: "OwnershipRenounced", type: "error" },
  { inputs: [], name: "PreviousChapterRequired", type: "error" },
  { inputs: [], name: "ReaderExists", type: "error" },
  { inputs: [], name: "ReaderNotExists", type: "error" },
  { inputs: [], name: "ReferrerChapterInactive", type: "error" },
  { inputs: [], name: "ReferrerNotExists", type: "error" },
  { inputs: [], name: "ReinvestTooDeep", type: "error" },
  { inputs: [], name: "TokenNotContract", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "ChapterPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "ChapterUnlocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "by", type: "address" },
    ],
    name: "ContractRenounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "open", type: "bool" },
    ],
    name: "LibraryOpenChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "place", type: "uint8" },
    ],
    name: "NewReaderPlace",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "OwnerAddressAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "permille",
        type: "uint16",
      },
    ],
    name: "PlatformFeePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "readerId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "referrerId",
        type: "uint256",
      },
    ],
    name: "ReaderJoined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "currentReferrer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "Reinvest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RewardTokenPayoutFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "contractBalance",
        type: "uint256",
      },
    ],
    name: "RewardTokenPayoutSkipped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RoyaltyAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RoyaltyClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      {
        indexed: false,
        internalType: "uint8",
        name: "uplineLevel",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UnilevelRoyaltyPayout",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "intended",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "actual",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UplinePayoutFallback",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "referrer", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "BoostBothTracks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "referrer", type: "address" },
      { internalType: "uint8", name: "track", type: "uint8" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "BoostTrack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "LAST_CHAPTER",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLATFORM_FEE_PERCENT",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROYALTY_PERCENT",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNILEVEL_PERCENT",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "accRoyaltyPerPoint",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adminRenounced",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "track", type: "uint8" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "buyNewChapter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint8", name: "", type: "uint8" },
      { internalType: "uint8", name: "", type: "uint8" },
    ],
    name: "cachedQualifiedUpline",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "chapterPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimRoyalty",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "readerAddr", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "findFreeTrack1Referrer",
    outputs: [
      { internalType: "address", name: "freeReferrer", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "readerAddr", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "findFreeTrack2Referrer",
    outputs: [
      { internalType: "address", name: "freeReferrer", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getChapterPrices",
    outputs: [
      { internalType: "uint256[13]", name: "prices", type: "uint256[13]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGlobalChapterStats",
    outputs: [
      { internalType: "uint256[13]", name: "t1Unlocked", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t2Unlocked", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t1Purch", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t2Purch", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t1Rev", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t2Rev", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t1Earn", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t2Earn", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t1Cycles", type: "uint256[13]" },
      { internalType: "uint256[13]", name: "t2Cycles", type: "uint256[13]" },
      {
        internalType: "uint256[13]",
        name: "royaltyContrib",
        type: "uint256[13]",
      },
      {
        internalType: "uint256[13]",
        name: "platformFees",
        type: "uint256[13]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "getReaderTotals",
    outputs: [
      { internalType: "uint256", name: "track1TotalEarned", type: "uint256" },
      { internalType: "uint256", name: "track2TotalEarned", type: "uint256" },
      { internalType: "uint256", name: "track1TotalCycles", type: "uint256" },
      { internalType: "uint256", name: "track2TotalCycles", type: "uint256" },
      { internalType: "uint256", name: "track1Unlocked", type: "uint256" },
      { internalType: "uint256", name: "track2Unlocked", type: "uint256" },
      { internalType: "uint256", name: "royaltyAvailable", type: "uint256" },
      { internalType: "uint256", name: "royaltyClaimed", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address[]", name: "addrs", type: "address[]" }],
    name: "getReadersBatchTotals",
    outputs: [
      { internalType: "uint256[]", name: "t1Earn", type: "uint256[]" },
      { internalType: "uint256[]", name: "t2Earn", type: "uint256[]" },
      { internalType: "uint256[]", name: "t1Cycles", type: "uint256[]" },
      { internalType: "uint256[]", name: "t2Cycles", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalReaders",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "getTrack1",
    outputs: [
      { internalType: "address", name: "currentReferrer", type: "address" },
      { internalType: "address[]", name: "referrals", type: "address[]" },
      { internalType: "bool", name: "blocked", type: "bool" },
      { internalType: "uint256", name: "reinvestCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "getTrack2",
    outputs: [
      { internalType: "address", name: "currentReferrer", type: "address" },
      { internalType: "address[]", name: "firstLine", type: "address[]" },
      { internalType: "address[]", name: "secondLine", type: "address[]" },
      { internalType: "bool", name: "blocked", type: "bool" },
      { internalType: "uint256", name: "reinvestCount", type: "uint256" },
      { internalType: "address", name: "closedPart", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalPlatformFeeCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalRoyaltyContrib",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "globalTotalPlatformFees",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "globalTotalRoyaltyContrib",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "globalTotalUnilevelPaid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1ChapterEarnings",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1ChapterRecycles",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1Purchases",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1Revenue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1UnilevelPaid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack1UnlockedCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2ChapterEarnings",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2ChapterRecycles",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2Purchases",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2Revenue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2UnilevelPaid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "globalTrack2UnlockedCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "idToAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "isReaderExists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "referrerAddress", type: "address" },
    ],
    name: "joinLibrary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastReaderId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "libraryOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownershipRenounced",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWalletA",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWalletB",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "readers",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "referrer", type: "address" },
      { internalType: "uint256", name: "partnersCount", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalReaderRoyaltyPoints",
        type: "uint256",
      },
      { internalType: "uint256", name: "royaltyDebt", type: "uint256" },
      { internalType: "uint256", name: "royaltiesClaimed", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "royaltyPot",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "open_", type: "bool" }],
    name: "setLibraryOpen",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRoyalties",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRoyaltyPoints",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdt",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "viewRoyalty",
    outputs: [{ internalType: "uint256", name: "available", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "viewRoyaltyPercent",
    outputs: [{ internalType: "uint256", name: "percent", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];

export const USDT_ABI = [
  {
    constant: false,
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    type: "function",
  },
] as const;

export const CHAPTER_NAMES = {
  1: "Chapter 1: The Beginning",
  2: "Chapter 2: Rising Action",
  3: "Chapter 3: The Challenge",
  4: "Chapter 4: Transformation",
  5: "Chapter 5: Mastery",
  6: "Chapter 6: Expansion",
  7: "Chapter 7: Leadership",
  8: "Chapter 8: Legacy",
  9: "Chapter 9: Rico Leap",
  10: "Chapter 10: Infinite Possibilities",
  11: "Chapter 11: The Matrix",
  12: "Chapter 12: Enlightenment",
};

export const TRACK_NAMES = {
  1: "X3 Matrix Track",
  2: "X6 Matrix Track",
} as const;
