export const CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`;
export const USDT_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_USDT_CONTRACT_ADDRESS as `0x${string}`;
export const TOKEN_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS as `0x${string}`;

export const CONTRACT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "v1Address", type: "address" },
      { internalType: "address", name: "usdtAddress", type: "address" },
      { internalType: "address", name: "rewardTokenAddress", type: "address" },
      { internalType: "address", name: "feeWalletA", type: "address" },
      { internalType: "address", name: "feeWalletB", type: "address" },
      { internalType: "address", name: "feeWalletC", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AdminRenounced", type: "error" },
  { inputs: [], name: "AlreadyMigrated", type: "error" },
  { inputs: [], name: "BadBucketSum", type: "error" },
  { inputs: [], name: "BadChapter1", type: "error" },
  { inputs: [], name: "BadReferrerState", type: "error" },
  { inputs: [], name: "ChapterAlreadyUnlocked", type: "error" },
  { inputs: [], name: "InvalidChapter", type: "error" },
  { inputs: [], name: "InvalidTrack", type: "error" },
  { inputs: [], name: "LibraryClosed", type: "error" },
  { inputs: [], name: "NoLegacyRoyalty", type: "error" },
  { inputs: [], name: "NoRicoToClaim", type: "error" },
  { inputs: [], name: "NoRoyalty", type: "error" },
  { inputs: [], name: "NotInV1", type: "error" },
  { inputs: [], name: "NotMigrated", type: "error" },
  { inputs: [], name: "OnlyAdmin", type: "error" },
  { inputs: [], name: "OnlyOwner", type: "error" },
  { inputs: [], name: "OwnershipRenounced", type: "error" },
  { inputs: [], name: "PreviousChapterRequired", type: "error" },
  { inputs: [], name: "ReaderExists", type: "error" },
  { inputs: [], name: "ReaderNotExists", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "ReferrerChapterInactive", type: "error" },
  { inputs: [], name: "ReferrerNotExists", type: "error" },
  { inputs: [], name: "TokenNotContract", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "V1CallFailed", type: "error" },
  { inputs: [], name: "X6Overflow", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "ChapterPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "ChapterUnlocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "by", type: "address" },
    ],
    name: "ContractRenounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "LegacyRoyaltyClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "open", type: "bool" },
    ],
    name: "LibraryOpenChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "v1Id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
    ],
    name: "Migrated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "place", type: "uint8" },
    ],
    name: "NewReaderPlace",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "readerId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "referrerId",
        type: "uint256",
      },
    ],
    name: "ReaderJoined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "currentReferrer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "Reinvest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "usdtBasis",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ricoAmount",
        type: "uint256",
      },
    ],
    name: "RicoAccrued",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RicoClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RoyaltyAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RoyaltyClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: false, internalType: "uint8", name: "track", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "chapter", type: "uint8" },
      {
        indexed: false,
        internalType: "uint8",
        name: "uplineLevel",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UnilevelRoyaltyPayout",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "intended",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "actual",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UplinePayoutFallback",
    type: "event",
  },
  {
    inputs: [],
    name: "LAST_CHAPTER",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LEADERBOARD_SIZE",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RICO_PER_USDT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROYALTY_PERCENT",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "V1",
    outputs: [
      { internalType: "contract IRicoMatrixV1", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "accRoyaltyPerPoint",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adminRenounced",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "track", type: "uint8" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "buyNewChapter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    name: "chapterPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "claimLegacyRoyalty",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "claimRico",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimRoyaltyV2",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "readerAddr", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "findFreeTrack1Referrer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "readerAddr", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "findFreeTrack2Referrer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getChapterPrices",
    outputs: [
      { internalType: "uint256[13]", name: "prices", type: "uint256[13]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getMigrationAndRoyaltyUI",
    outputs: [
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "uint256", name: "v1RoyaltyPercent", type: "uint256" },
      { internalType: "uint256", name: "legacyClaimable", type: "uint256" },
      { internalType: "uint256", name: "v2Claimable", type: "uint256" },
      { internalType: "uint256", name: "totalClaimable", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "getReaderSummary",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "referrer", type: "address" },
          { internalType: "uint256", name: "partnersCount", type: "uint256" },
          {
            internalType: "uint256",
            name: "track1TotalEarned",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "track2TotalEarned",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "track1TotalCycles",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "track2TotalCycles",
            type: "uint256",
          },
          { internalType: "uint256", name: "track1Unlocked", type: "uint256" },
          { internalType: "uint256", name: "track2Unlocked", type: "uint256" },
          {
            internalType: "uint256",
            name: "royaltyAvailable",
            type: "uint256",
          },
          { internalType: "uint256", name: "royaltyClaimed", type: "uint256" },
          { internalType: "uint256", name: "royaltyPercent", type: "uint256" },
          { internalType: "uint256", name: "ricoShouldHave", type: "uint256" },
          { internalType: "uint256", name: "ricoSent", type: "uint256" },
          { internalType: "uint256", name: "ricoPending", type: "uint256" },
        ],
        internalType: "struct RICOMATRIX.ReaderSummary",
        name: "s",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getRicoFarming",
    outputs: [
      { internalType: "uint256", name: "shouldHave", type: "uint256" },
      { internalType: "uint256", name: "sent", type: "uint256" },
      { internalType: "uint256", name: "pending", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTopEarners",
    outputs: [
      { internalType: "address[8]", name: "addrs", type: "address[8]" },
      { internalType: "uint256[8]", name: "amounts", type: "uint256[8]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTopReferrers",
    outputs: [
      { internalType: "address[8]", name: "addrs", type: "address[8]" },
      { internalType: "uint256[8]", name: "counts", type: "uint256[8]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalReaders",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "getTrack1",
    outputs: [
      { internalType: "address", name: "currentReferrer", type: "address" },
      { internalType: "address[]", name: "referrals", type: "address[]" },
      { internalType: "bool", name: "blocked", type: "bool" },
      { internalType: "uint256", name: "reinvestCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint8", name: "chapter", type: "uint8" },
    ],
    name: "getTrack2",
    outputs: [
      { internalType: "address", name: "currentReferrer", type: "address" },
      { internalType: "address[]", name: "firstLine", type: "address[]" },
      { internalType: "address[]", name: "secondLine", type: "address[]" },
      { internalType: "bool", name: "blocked", type: "bool" },
      { internalType: "uint256", name: "reinvestCount", type: "uint256" },
      { internalType: "address", name: "closedPart", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "idToAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "isReaderExists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "referrerAddress", type: "address" },
    ],
    name: "joinLibrary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastReaderId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyClaimedOnV2",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyRoyaltyClaimedV1",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyRoyaltyPercentV1",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyRoyaltySnapshot",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyShareImported",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacySharePoints",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyTrack1TotalCycles",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyTrack1TotalEarned",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyTrack2TotalCycles",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "legacyTrack2TotalEarned",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "libraryOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "migrateSelf",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "migratedFromV1",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "migrationStatus",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownershipRenounced",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWalletA",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWalletB",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWalletC",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "readers",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "referrer", type: "address" },
      { internalType: "uint256", name: "partnersCount", type: "uint256" },
      { internalType: "uint256", name: "royaltyPoints", type: "uint256" },
      { internalType: "uint256", name: "royaltyDebt", type: "uint256" },
      { internalType: "uint256", name: "royaltiesClaimedV2", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "ricoClaimed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "ricoExpected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "royaltyPot",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "open_", type: "bool" }],
    name: "setLibraryOpen",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "topEarners",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "topEarnings",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "topReferralCounts",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "topReferrers",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRoyalties",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRoyaltyPoints",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "totalUnilevelEarned",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdt",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "v1IdOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "viewLegacyClaimable",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "viewRicoPending",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "viewRoyaltyPercentV2",
    outputs: [{ internalType: "uint256", name: "percent", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "readerAddr", type: "address" }],
    name: "viewRoyaltyV2",
    outputs: [{ internalType: "uint256", name: "available", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];  
export const USDT_ABI = [
  {
    constant: false,
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    type: "function",
  },
] as const;

export const CHAPTER_NAMES = {
  1: "Chapter 1: How to Discover your Life Purpose",
  3: "Chapter 3: Mastering Best Crypto Security: Protect Your Digital Wealth",
  2: "Chapter 2: Trading Without Illusions: A Simple, Data-First DYOR Guide",
  4: "Chapter 4: Why Most People Never Build Wealth",
  5: "Chapter 5: Why People Get Rich Doing One Thing… Then Lose It All Doing Another",
  6: "Chapter 6: Why wise Parent buy Travel",
  7: "Chapter 7: Holy DEFI",
  8: "Chapter 8: Legacy",
  9: "Chapter 9: Rico Leap",
  10: "Chapter 10: Infinite Possibilities",
  11: "Chapter 11: The Matrix",
  12: "Chapter 12: Enlightenment",
};

export const TRACK_NAMES = {
  1: "X3 Matrix Track",
  2: "X6 Matrix Track",
} as const;
