export const RICO_MATRIX_HUB_ABI = [
  {
    type: "event",
    name: "JoinedHub",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "referrer", type: "address" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "totalUSD", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ChapterPurchasedHub",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "track", type: "uint8" },
      { indexed: false, name: "startCh", type: "uint8" },
      { indexed: false, name: "endCh", type: "uint8" },
      { indexed: false, name: "totalUSD", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "UserBoostedHub",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "referrer", type: "address" },
      { indexed: false, name: "track", type: "uint8" },
      { indexed: false, name: "chapter", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "readers",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "referrer", type: "address" },
      { name: "partnersCount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "chapterPrice",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isSupportedPaymentToken",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "ricoExpected",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "ricoClaimed",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "viewRicoPending",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalUnilevelEarned",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastReaderId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteSyncFee",
    stateMutability: "view",
    inputs: [{ name: "targetEid", type: "uint32" }],
    outputs: [{ name: "nativeFee", type: "uint256" }],
  },
  {
    type: "function",
    name: "syncUserToSpoke",
    stateMutability: "payable",
    inputs: [{ name: "targetEid", type: "uint32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "joinLibraryHub",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "referrerAddress", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "joinLibraryHubWithPermit2",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "referrerAddress", type: "address" },
      { name: "permitAmount", type: "uint256" },
      { name: "permitNonce", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "buyChapterBatchHub",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "track", type: "uint8" },
      { name: "startCh", type: "uint8" },
      { name: "endCh", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "buyChapterBatchHubWithPermit2",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "track", type: "uint8" },
      { name: "startCh", type: "uint8" },
      { name: "endCh", type: "uint8" },
      { name: "permitAmount", type: "uint256" },
      { name: "permitNonce", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimRico",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getReaderFullSummary",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "referrer", type: "address" },
      { name: "partnersCount", type: "uint256" },
      { name: "track1Unlocked", type: "uint8" },
      { name: "track2Unlocked", type: "uint8" },
      { name: "track1TotalEarnedUSD", type: "uint256" },
      { name: "track2TotalEarnedUSD", type: "uint256" },
      { name: "track1TotalCycles", type: "uint256" },
      { name: "track2TotalCycles", type: "uint256" },
      { name: "royaltyAvailableUSD", type: "uint256" },
      { name: "royaltyClaimedUSD", type: "uint256" },
      { name: "royaltyPercentOfPoolBps", type: "uint256" },
      { name: "ricoShouldHave", type: "uint256" },
      { name: "ricoSent", type: "uint256" },
      { name: "ricoPending", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getTopEarners",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "addrs", type: "address[8]" },
      { name: "amounts", type: "uint256[8]" },
    ],
  },
  {
    type: "function",
    name: "getTopReferrers",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "addrs", type: "address[8]" },
      { name: "counts", type: "uint256[8]" },
    ],
  },
  {
    type: "function",
    name: "getTrack1Info",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "chapter", type: "uint8" },
    ],
    outputs: [
      { name: "currentReferrer", type: "address" },
      { name: "referralsCount", type: "uint256" },
      { name: "blocked", type: "bool" },
      { name: "reinvestCount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getTrack2Info",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "chapter", type: "uint8" },
    ],
    outputs: [
      { name: "currentReferrer", type: "address" },
      { name: "firstLineCount", type: "uint256" },
      { name: "secondLineCount", type: "uint256" },
      { name: "blocked", type: "bool" },
      { name: "reinvestCount", type: "uint256" },
      { name: "closedPart", type: "address" },
    ],
  },
  {
    type: "function",
    name: "getTrack1Referrals",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "chapter", type: "uint8" },
    ],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "getTrack2Referrals",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "chapter", type: "uint8" },
    ],
    outputs: [
      { name: "firstLine", type: "address[]" },
      { name: "secondLine", type: "address[]" },
    ],
  },
] as const;

// Matches src/periphery/RoyaltyVault.sol (Ricomatrix V3 Foundry project)
// exactly — royalty claims go to this contract, never to the Hub
// (RICO_MATRIX_HUB_ABI above has no claim function at all). claimRoyalty
// itself caps the payout to both the accounted USD pot AND the vault's
// actual on-hand balance of the chosen token (never reverts for a low
// balance alone — only if that token's balance is zero), so
// viewClaimableInToken mirrors that same capping and is the only reliable
// way to know in advance whether a token can pay out the FULL claim.
export const ROYALTY_VAULT_ABI = [
  {
    type: "function",
    name: "claimRoyalty",
    stateMutability: "nonpayable",
    inputs: [{ name: "paymentToken", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "viewPendingRoyalty",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "viewClaimableInToken",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "paymentToken", type: "address" },
    ],
    outputs: [
      { name: "availableUSD", type: "uint256" },
      { name: "rawAmount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "RoyaltyClaimed",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amountUSD", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;

// Matches RicoGiveawayEngine.sol. recordDirectJoin/recordChapterPurchase are
// onlyOwner/onlyAuthorized(hub) and deliberately omitted — no user wallet can
// ever call them, so the frontend never should either. The only writes a
// user's own wallet can make are the self-import and the claim.
export const RICO_GIVEAWAY_ENGINE_ABI = [
  {
    type: "function",
    name: "importMyHistoricalEarnings",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "claimRicoReward",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ name: "claimable", type: "uint256" }],
  },
  {
    type: "function",
    name: "isActive",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "isUserImported",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getPendingRico",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "ricoDecimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "firstMilestoneUSD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "milestoneStepUSD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUserFullEarningsBreakdown",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "histTrack1USD", type: "uint256" },
      { name: "histTrack2USD", type: "uint256" },
      { name: "histTotalUSD", type: "uint256" },
      { name: "activeReferralUSD", type: "uint256" },
      { name: "activePersonalUSD", type: "uint256" },
      { name: "totalCombinedVolumeUSD", type: "uint256" },
      { name: "completedMilestones", type: "uint256" },
      { name: "nextMilestoneTargetUSD", type: "uint256" },
      { name: "totalClaimableRico", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getGlobalStats",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "campaignActive", type: "bool" },
      { name: "activatedAt", type: "uint256" },
      { name: "totalFunded", type: "uint256" },
      { name: "totalDistributed", type: "uint256" },
      { name: "totalClaimed", type: "uint256" },
      { name: "activeVolumeUSD", type: "uint256" },
      { name: "totalDropsCount", type: "uint256" },
      { name: "contractBalance", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getThroneRecordsPaginated",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [
      {
        name: "records",
        type: "tuple[]",
        components: [
          { name: "winner", type: "address" },
          { name: "milestoneUSD", type: "uint256" },
          { name: "rewardRico", type: "uint256" },
          { name: "timestamp", type: "uint256" },
          { name: "isHistoricalImport", type: "bool" },
        ],
      },
      { name: "total", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "HistoricalUserImported",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "track1EarnedUSD", type: "uint256" },
      { indexed: false, name: "track2EarnedUSD", type: "uint256" },
      { indexed: false, name: "totalPastVolumeUSD", type: "uint256" },
      { indexed: false, name: "milestonesCompleted", type: "uint256" },
      { indexed: false, name: "nextMilestoneTargetUSD", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ThroneMilestoneAchieved",
    inputs: [
      { indexed: true, name: "winner", type: "address" },
      { indexed: false, name: "milestoneUSD", type: "uint256" },
      { indexed: false, name: "rewardRico", type: "uint256" },
      { indexed: false, name: "throneCount", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RicoClaimed",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const RICO_MATRIX_SPOKE_ABI = [
  {
    type: "event",
    name: "OrderSubmitted",
    inputs: [
      { indexed: true, name: "orderId", type: "bytes32" },
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "referrer", type: "address" },
      { indexed: false, name: "kind", type: "uint8" },
      { indexed: false, name: "totalUSD", type: "uint256" },
      { indexed: false, name: "hubToken", type: "address" },
      { indexed: false, name: "rail", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "StatusSynced",
    inputs: [
      { indexed: false, name: "user", type: "address" },
      { indexed: false, name: "t1Unlocked", type: "uint8" },
      { indexed: false, name: "t2Unlocked", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "localView",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "referrer", type: "address" },
      { name: "t1Unlocked", type: "uint8" },
      { name: "t2Unlocked", type: "uint8" },
      { name: "partnersCount", type: "uint256" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "chapterPrice",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isSupportedPaymentToken",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "estimateJoinCost",
    stateMutability: "view",
    inputs: [{ name: "paymentToken", type: "address" }],
    outputs: [
      { name: "totalUSD", type: "uint256" },
      { name: "rawTokenAmount", type: "uint256" },
      { name: "lzFee", type: "uint256" },
      { name: "bridgeFee", type: "uint256" },
      { name: "totalNativeFee", type: "uint256" },
      { name: "rail", type: "uint8" },
      { name: "hubToken", type: "address" },
    ],
  },
  {
    type: "function",
    name: "estimateChapterBuyCost",
    stateMutability: "view",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "startCh", type: "uint8" },
      { name: "endCh", type: "uint8" },
    ],
    outputs: [
      { name: "totalUSD", type: "uint256" },
      { name: "rawTokenAmount", type: "uint256" },
      { name: "lzFee", type: "uint256" },
      { name: "bridgeFee", type: "uint256" },
      { name: "totalNativeFee", type: "uint256" },
      { name: "rail", type: "uint8" },
      { name: "hubToken", type: "address" },
    ],
  },
  {
    type: "function",
    name: "quoteJoinFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "nativeFee", type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteChapterBuyFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "nativeFee", type: "uint256" }],
  },
  {
    type: "function",
    name: "joinLibrarySpoke",
    stateMutability: "payable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "referrerAddress", type: "address" },
      { name: "lzFee", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "buyChapterSpoke",
    stateMutability: "payable",
    inputs: [
      { name: "paymentToken", type: "address" },
      { name: "track", type: "uint8" },
      { name: "startCh", type: "uint8" },
      { name: "endCh", type: "uint8" },
      { name: "lzFee", type: "uint256" },
    ],
    outputs: [],
  },
] as const;
